spring.application.name=employeegcp

# GCP Spanner Configuration
spring.cloud.gcp.project-id=caramel-thinker-460410-t2
spring.cloud.gcp.spanner.instance-id=learn-java-abhishek
spring.cloud.gcp.spanner.database=employee-db

# Use absolute path to credentials (MUST use file: prefix)
spring.cloud.gcp.credentials.location=file:/C:/Users/DELL/Desktop/GCP/caramel-thinker-460410-t2-eace8c29b700.json

# Disable default JDBC auto-configuration (because we're not using a traditional SQL DB)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
